### PR TITLE
Updated to Web API 2 / .NET 4.5

### PR DESCRIPTION
**Pull request by AlexZeitler**
Also updated Windsor Dependencies...

### CODE REVIEW

**Comment by filipw** [comment]
:+1:

**Comment by AlexZeitler** [comment]
Thanks,

NuGet Packages are built automatically?

Alex

**Comment by filipw** [comment]
no I think we need @ChrisMissal

**Comment by pedroreys** [comment]
Yeah, Chris does the nuget thing

**Comment by ChrisMissal** [comment]
I can publish. It's version 0.10.0 right now, should this be version 1.0.0 or 0.11.0 ?

**Comment by panesofglass** [comment]
Let's bump to 1.0

**Comment by ChrisMissal** [comment]
:+1:

**Comment by AlexZeitler** [comment]
For me both is ok

Thanks

Alex

Am 22.10.2014 um 17:12 schrieb Chris Missal <notifications@github.com<mailto:notifications@github.com>>:

I can publish. It's version 0.10.0 right now, should this be version 1.0.0 or 0.11.0 ?

**Comment by AlexZeitler** [comment]
Just wanted to ask when the updated package will be published.

Is there a reason why we don’t automate the publishing process?

Thanks,

Alex

**Comment by ChrisMissal** [comment]
Hey, yeah, I can get it published in a moment. There's no reason other than
the time to get it all set up. If anybody wants to take charge of that, I'm
all for it.

On Thu, Oct 30, 2014 at 4:13 PM, Alexander Zeitler <notifications@github.com

> wrote:
> 
> Just wanted to ask when the updated package will be published.
> 
> Is there a reason why we don’t automate the publishing process?
> 
> Thanks,
> 
> Alex
> 
> From: Chris Missal [mailto:notifications@github.com]
> Sent: Mittwoch, 22. Oktober 2014 17:13
> To: WebApiContrib/WebApiContrib.IoC.CastleWindsor
> Cc: Alexander Zeitler
> Subject: Re: [WebApiContrib.IoC.CastleWindsor] Updated to Web API 2 / .NET
> 4.5 (#5)
> 
> I can publish. It's version 0.10.0 right now, should this be version 1.0.0
> or 0.11.0 ?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/WebApiContrib/WebApiContrib.IoC.CastleWindsor/pull/5#issuecomment-60100684>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebApiContrib/WebApiContrib.IoC.CastleWindsor/pull/5#issuecomment-61170509
> .

## 

_Chris Missal | *Senior Consultant | *Headspring_

**Comment by AlexZeitler** [comment]
:thumbsup:
I could provide a Jenkins for that and set it up.

**Comment by ChrisMissal** [comment]
I'd be shocked if anybody was opposed, I say go for it! :)

On Thu, Oct 30, 2014 at 4:41 PM, Alexander Zeitler <notifications@github.com

> wrote:
> 
> I could provide a Jenkins for that and set it up.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebApiContrib/WebApiContrib.IoC.CastleWindsor/pull/5#issuecomment-61174588
> .

## 

_Chris Missal | *Senior Consultant | *Headspring_

**Comment by AlexZeitler** [comment]
Is it ok to move the build script to FAKE?
That would make things a bit easier.

**Comment by ChrisMissal** [comment]
No argument here, I like FAKE.

On Mon, Nov 17, 2014 at 4:03 PM, Alexander Zeitler <notifications@github.com

> wrote:
> 
> Is it ok to move the build script to FAKE?
> That would make things a bit easier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebApiContrib/WebApiContrib.IoC.CastleWindsor/pull/5#issuecomment-63384533
> .

## 

_Chris Missal | *Senior Consultant | *Headspring_

**Comment by panesofglass** [comment]
@AlexZeitler yes, please!

**Pull request merged**
